### ISSUE TITLE
embed tests that use OpenSSL are not thread safe and fail sporadically.

### ISSUE THREAD

**Issue by duggaraju** [contentauth/c2pa-rs#400]
Easy to repro on a machine with multiple CPUs. Looks like open SSL has shared state and running multiple tests that use Open SSL can fail.

Run 
```bash
cargo test --lib --all-features test_embed_
```

You will see errors like
failures:

---- manifest::tests::test_embed_sidecar_with_parent_manifest stdout ----
thread 'manifest::tests::test_embed_sidecar_with_parent_manifest' panicked at sdk/src/utils/test.rs:325:18:
get_temp_signer: BadParam("certificate chain is not in correct order")

---- manifest::tests::test_embed_sidecar_user_label stdout ----
thread 'manifest::tests::test_embed_sidecar_user_label' panicked at sdk/src/utils/test.rs:325:18:
get_temp_signer: BadParam("certificate chain is not in correct order")

---- manifest::tests::test_embed_stream stdout ----
thread 'manifest::tests::test_embed_stream' panicked at sdk/src/utils/test.rs:325:18:
get_temp_signer: BadParam("certificate chain is not in correct order")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Now run the same sequentially
```bash
cargo test --all-features test_embed_ -- --test-threads=1
```
Now all the tests pass fine.

**Comment by mauricefisher64** [comment]
Fixed
